spring.application.name=BookMyShow


spring.datasource.url= jdbc:mysql://localhost:3306/BMS?createDatabaseIfNotExist=true
spring.datasource.username= root
spring.datasource.password= satyam

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port= 8080
